FROM node:18-slim

RUN mkdir -p /app
WORKDIR /app

COPY shared ./shared

RUN mkdir -p /app/client
WORKDIR /app/client

COPY client/package.json client/yarn.lock ./
RUN yarn install

COPY client ./

EXPOSE 5173

CMD ["yarn", "dev", "--host", "0.0.0.0"]

